### ISSUE TITLE
Materialise the OWL types also for SOLR

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/vfb-pipeline-dumps#2]
Make sure that the same logic that is applied to the neo4j ingest is also apply to sole documents, and added to the:

 `facets_annotation` field

Make sure the KB labels are added as well

**Comment by matentzn** [comment]
I have reviewed that it happens by checking http://virtualflybrain.org/data/VFB/OWL/raw/ (the file inferred_annotation.owl).

**Comment by matentzn** [comment]
This works in my tests as well, so I will leave it to @Robbie1977 to confirm (check after next pipeline run solr.json, wether it has non-KB `facet_annotations`)

**Comment by Robbie1977** [comment]
All appear correct in SOLR
