### ISSUE TITLE
Redundancy stripping broken

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-pipeline-dumps#27]
Reundancy stripping on individuals is broken, e.g. only the middle classification on this individual should be present after redundancy stripping

<img width="806" alt="image" src="https://user-images.githubusercontent.com/112839/158217497-3c12b370-caf7-45ea-8d18-c0e08082aa20.png">

Probably missing `robot reduce` step in new pipeline.

**Comment by dosumis** [comment]
Rather than running the whole pipeline, do we have a meaty enough machine to just test run this step?

**Comment by Robbie1977** [comment]
@hkir-dev the fix you applied doesn't seem to be resolving the example @dosumis raised 

After latest load: https://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=VFB_jrchk7jm&i=VFB_00101567,VFB_jrchk7jm  

![image](https://user-images.githubusercontent.com/4630768/160374287-57fb2e7c-1c45-45ac-90bb-c67a3e2c864c.png)
