### ISSUE TITLE
Add post reasoning SPARQL-based semantic tagging step.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-pipeline-dumps#48]
This step should use ROBOT to add tags and should run after both reasoning and connectomics data merge.

We need a new keyword for (name prefix) for SPARQL file names to indicate this

constructReasoned_{fu}.sparql

SOLR loading needs to take all labels (tags), but doesn't need connectomics data.  This can work because because files with tags are separate from the files/sources used to generate them.

**Comment by hkir-dev** [comment]
PR created https://github.com/VirtualFlyBrain/vfb-pipeline-dumps/pull/50
