### ISSUE TITLE
Enable filtering by neo label and IRI pattern

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/vfb-pipeline-dumps#6]
We do not want any entities in the SOLR ingest to correspond to the label X or the URL pattern Y. Make this configurable.

**Comment by matentzn** [comment]
There is a new section in the [config file](https://github.com/VirtualFlyBrain/vfb-prod/blob/master/neo4j2owl-config.yaml) called `filters` which should be pretty self explanatory. The main thing to know is that the ['iri_prefix'] [filter](https://github.com/VirtualFlyBrain/vfb-pipeline-dumps/blob/5aa5d27e89fd442b3b9635bb3e851c24590906eb/scripts/obographs-solr.py#L86) actually checks whether the listed string is contained somewhere in the IRI - so in our case, `VFBc_` would have worked as well. Saver like that.

**Comment by matentzn** [comment]
@Robbie1977 can you double check this? I checked the resulting solr.json file with the new config and it seemed to have worked!

**Comment by Robbie1977** [comment]
Yep no VFBc are now in the solar index.
