### ISSUE TITLE
Can we modify the solr config to use Strings rather than lists for short_form and label

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/vfb-pipeline-dumps#7]
If this a relatively simple change can we just change the solr.json to have a Sting rather than [String] for the short_form and the label fields? 

These are single entry Items so a simple take first record should suffice.

**Comment by Robbie1977** [comment]
current format:
```
{
facets_annotation: [
"NBLAST",
"Neuron",
"VFB",
"Nervous_system",
"Adult",
"Individual",
"Cell",
"Anatomy"
],
id: "http://virtualflybrain.org/reports/VFB_00000001",
label: [
"fru-M-200266"
],
short_form: [
"VFB_00000001"
],
synonym: [
"fru-M-200266",
"FruMARCM-M002262_seg001"
]
},
```
https://solr.p2.virtualflybrain.org/solr/ontology/select?json=%7B%22params%22:%7B%22q%22:%22VFB_00000001+OR+t*+OR+*t*%22,%22defType%22:%22edismax%22,%22qf%22:%22label+synonym+label_autosuggest_ws+label_autosuggest_e+label_autosuggest+synonym_autosuggest_ws+synonym_autosuggest+shortform_autosuggest%22,%22indent%22:%22true%22,%22fl%22:%22short_form,label,synonym,id,facets_annotation%22,%22start%22:%220%22,%22fq%22:[%22shortform_autosuggest:VFB*+OR+shortform_autosuggest:FB*+OR+is_defining_ontology:true%22],%22rows%22:%22100%22,%22wt%22:%22json%22,%22bq%22:%22shortform_autosuggest:VFB*%5E110.0+shortform_autosuggest:FBbt*%5E100.0+is_defining_ontology:true%5E100.0+label_s:%5C%22%5C%22%5E2+synonym_s:%5C%22%5C%22+short_form:FBbt_00003982%5E2%22%7D%7D

Required format:
id: "vfb:individual:http://virtualflybrain.org/reports/VFB_00000001",
short_form: "VFB_00000001",
label: "fru-M-200266",
synonym: [
"fru-M-200266",
"FruMARCM-M002262_seg001"
],
facets_annotation: [
"Individual",
"VFB",
"_Individual",
"NBLAST",
"Neuron",
"Anatomy",
"Cell",
"Entity"
]
```

**Comment by matentzn** [comment]
After discussion, probably a problem with solr.
